### ISSUE TITLE
[피스] 글 컴포넌트

### ISSUE THREAD

**Issue by shinkeonkim** [today-they-learned/peacepiece_front#17]
https://www.figma.com/file/hHSBqwFaqELSdNDWIPzZZM/peacepiece?node-id=218%3A250

별도로 컴포넌트를 더미 데이터로 만들고, 

나중에 피스 페이지 레이아웃 나오면 그때 연결하기

세세한 디자인은 이후에 하기..!

구성 요소

- 아바타 이미지 (avatar_url)
- 글 작성자 이름 (author)
- 글 작성 일자 (created_at)

- 첨부된 사진들(images)
images: [ { id: 1, image_url: '', id: 2, image_url: ''} ]
- 글 내용 (content)

아래 참고

```
{
  id: 1,
  content: '글 내용',
  created_at: '날짜',
  updated_at: '날짜',
  images: [
    {
      id: 1,
      image_url: '이미지 URL'
    },
    {
      id: 1,
      image_url: '이미지 URL'
    },
  ],
  author: {
    id: 1,
    name: '이름',
    avatar_url: ''
  },
  recemt_comment: {
    id: 1,
    content: '',
    author: {
      id: 1,
      name: '이름',
      avatar_url: ''
    },
  }
}

```

더보기릏 했을 때, comments를 또 다시 불러올테니

```
{
  comments: [
    {
      id: 1,
      content: '',
      author: {
        id: 1,
        name: '이름',
        avatar_url: '',
      },
    },
    {
      id: 1,
      content: '',
      author: {
        id: 1,
        name: '이름',
        avatar_url: '',
      },
    }

  ]  
}
```

**Comment by minjj0905** [comment]
![Image](https://user-images.githubusercontent.com/55120738/184605790-ec7c9626-8a58-4cb1-b2c9-649d490f4e71.png

내가 해냄 여부는 옵션으로

**Comment by minjj0905** [comment]
종료된 경우에 다른점

1.  앞에 [종료]
![Image](https://user-images.githubusercontent.com/55120738/184606091-6a3afec7-79a1-4c6d-81b5-20fd1d19c4a4.png)

2. 문구 변경
![Image](https://user-images.githubusercontent.com/55120738/184606118-4f0edc4f-4433-40e5-abb6-02ec9568d7ef.png)

**Comment by minjj0905** [comment]
중간에 해시태그랑 포인트 소개 문구 같은 건 배너 컴포넌트 이용하면.. 될.. 듯?
