### ISSUE TITLE
영상 재생률 체크

### ISSUE THREAD

**Issue by shinkeonkim** [today-they-learned/peacepiece_front#18]

**Comment by minjj0905** [comment]
1. 실험실 안전교육 등의 영상 진도율 체크가 왜 2-3분짜리 영상 6-8페이지로 구분 되어 있는지 좀 알 것 같네요.... 영상 하나의 몇분까지 보았는지 체크하기엔 매우 번거로운 작업이 될 듯

**Comment by minjj0905** [comment]
2. 가상대학 어떻게 하는지 좀 알아보면 좋을..것..같은디...

**Comment by minjj0905** [comment]
https://codesandbox.io/s/react-videojs-currenttime-zvlbn

참고자료 ...

**Comment by minjj0905** [comment]
영상 재생 한 거 테이블을 어떻게 저장할거인지 고민해보면 좋을것같읍니다....
