### ISSUE TITLE
[챌린지] 위클리 챌린지 창 줄이면 카드 잘림

### ISSUE THREAD

**Issue by cychann** [today-they-learned/peacepiece_front#208]
<img width="655" alt="스크린샷 2022-09-11 오후 11 09 53" src="https://user-images.githubusercontent.com/66055587/189532495-a7cb8719-daaa-4011-8877-b38217a4756e.png">

**Comment by minjj0905** [comment]
fix in 7221c1f40d58fdb0f60f1ffe067944d26d0dfd3c
