### ISSUE TITLE
이번주 챌린지 카드 컴포넌트 제작

### ISSUE THREAD

**Issue by minjj0905** [today-they-learned/peacepiece_front#24]

**Comment by minjj0905** [comment]
개별 카드 

![Image](https://user-images.githubusercontent.com/55120738/183419379-69f74a0d-0afc-4c87-ba4e-fbc2d77cd478.png)

**Comment by soyekwon** [comment]
컴포넌트 이름 WeeklyChallengeCard로 하는 게 좋을까요? 이름이 너무 길어서 줄이고 싶은데 .. 
@minjj0905 @cychann @shinkeonkim
