### ISSUE TITLE
[Question] How did you manage your tokens?

### ISSUE THREAD

**Issue by seiwonpark** [today-they-learned/peacepiece_front#252]
Interesting project. Surfed through @shinkeonkim 's github.

So, currently I've been figuring out how to authenticate users.
There might be 2 choices in short, `token(like in this project)` and `session`.

---

And here's my question.

Guess 'Token Authentication using JWT' was implemented on this project but how did you manage your tokens?
I mean where did you store `access_token` and `refresh_token`?

Also wondering if you've set http-only cookie(which I'm not used to).

**Comment by shinkeonkim** [comment]
Thank you for your interest in this project.

To answer your question..

It was managed very simply.
Please refer to the following link for the client side.

On the server side, we used django jwt token related package

If you have any another question about client side, ask a question to @minjj0905 

https://github.com/today-they-learned/peacepiece_front/blob/main/src/config/api.ts

https://django-rest-framework-simplejwt.readthedocs.io/en/latest/

**Comment by seiwonpark** [comment]
Thanks for the answer and the information :) I'll contact her through her blog.
