### ISSUE TITLE
[공용] 슬라이더 컴포넌트 제작

### ISSUE THREAD

**Issue by minjj0905** [today-they-learned/peacepiece_front#33]

**Comment by soyekwon** [comment]
이거 프로필 모달창 할 때 만들어 놨어서 슬라이더 따로 컴포넌트로 빼놀게여

**Comment by minjj0905** [comment]
앗 이해 잘못한거같은데 슬라이더는 

![Image](https://user-images.githubusercontent.com/55120738/184603114-201d6e41-128a-4783-ac67-67410312d257.png)

이런거

**Comment by minjj0905** [comment]
단 직접만들면 매우 귀찮을 확률이 높으니 가아아아급적 라이브러리 활용해주세요 내부에 들어가는 컴포넌트만 좀 자율적으로 바꿀 수 있도록,, 아님 그냥 저 이번주 챌린지 배너 자체를 만들어도 상관없긴 함

근데 슬라이더 자체를 또 쓰더라구요 ,, 

![Image](https://user-images.githubusercontent.com/55120738/184603440-f3fdf854-bb93-4e07-985e-20183c2a27cf.png)

챌린지 상세임 여기는
그래서 각각 만드는게 편할거같으면 각각 만드시고 재활용 가능하게 할 수 있을거같으면 재활용되도록 만들면 될듯?

### 🔔 참고자료
https://react-slick.neostack.com/
https://learus.github.io/react-material-ui-carousel/
http://react-responsive-carousel.js.org/

**Comment by soyekwon** [comment]
아 토글이랑 헷갈렸네용 넹 !!

**Comment by soyekwon** [comment]
오 라이브러리 참고자료 감사용

**Comment by soyekwon** [comment]
지금 만들고 있는 데 각 각 만들어야 할 거 같앙
