### ISSUE TITLE
기본 버튼 컴포넌트 제작

### ISSUE THREAD

**Issue by minjj0905** [today-they-learned/peacepiece_front#37]

**Comment by minjj0905** [comment]
![Image](https://user-images.githubusercontent.com/55120738/183421413-6f77bbd3-92c8-4bd2-9b42-add36457cb00.png)

디자인은 동일하게 색상은 옵션으로 지정가능하게 하면 좋겠는데요

**Comment by soyekwon** [comment]
버튼 공통 컴포넌트 feature/3_modal 브랜치에 디자인은 동일하게 색상은 옵션으로 지정가능 하게 
FlexButton 만들어 놔서 그 브랜치 merge만 하면 될 듯 해염

**Comment by minjj0905** [comment]
엄지척

**Comment by soyekwon** [comment]
어우 근데 색상 버튼 배경색만 옵션으로 바꾸게 해놨어서

**Comment by soyekwon** [comment]
따로 브랜치 만들어서 글자색상도 옵션으로 바꿀 수 있게 해서 pr 올릴게염

**Comment by soyekwon** [comment]
아니다 modal 브랜치에서 수정해서 push 할게여

**Comment by soyekwon** [comment]
엥 아니네 글자색도 수정할 수 있게 해놨네

**Comment by soyekwon** [comment]
하하 바로 merge 하면 될듯영
