### ISSUE TITLE
ChallengeFigure 컴포넌트 분리

### ISSUE THREAD

**Issue by minjj0905** [today-they-learned/peacepiece_front#52]
![Image](https://user-images.githubusercontent.com/55120738/184607198-5548152a-5c74-4061-84e4-5c67cbc4f53c.png)

이 애매함.... 인원수/포인트 컴포넌트 뭔가 자주쓰는데 분리할까 ,,,, 근데 컴포넌트 이름 대체 뭐라고 해야할지 모르겠음

**Comment by minjj0905** [comment]
@shinkeonkim @cychann @soyekwon 의견.. 바람..니다...

**Comment by soyekwon** [comment]
음 방금 피그마 확인하고 왔는데 두 개가 다 붙어있길래 전 분리 안하는 게 좋은거 같아여
컴포넌트 이름은 ...

**Comment by soyekwon** [comment]
뭔가 목표 같은 느낌이라 targerlabel ??

**Comment by minjj0905** [comment]
ㅇㅇ 두개 같이 쌍으로 쓰는김에 그거 두개를 분리하자는 거여씀다

일단 의견 한개 감사

**Comment by cychann** [comment]
ChallengeFigure
